var searchData=
[
  ['recibirrespuesta_0',['recibirRespuesta',['../logica_usuario_8h.html#a0e0bdec3b995275b2eacab27596c8555',1,'recibirRespuesta(SOCKET sock, char *bufferRespuesta):&#160;logicaUsuario.c'],['../logica_usuario_8c.html#a0e0bdec3b995275b2eacab27596c8555',1,'recibirRespuesta(SOCKET sock, char *bufferRespuesta):&#160;logicaUsuario.c']]],
  ['recibirsolicitud_1',['recibirSolicitud',['../_pruebas_2_debug_usuario_2main_8h.html#a7663f006d9c623ea3bb76262b67d519b',1,'main.h']]],
  ['recibirsolicitudenlistasimple_2',['recibirSolicitudEnListaSimple',['../logica_servidor_8h.html#a7fe9c3b755bbb7c1bfa37350473fc2c5',1,'recibirSolicitudEnListaSimple(t_listaSimple *listaSimple, t_nodo ***nodoDelCliente, char *bufferSolicitud):&#160;logicaServidor.c'],['../logica_servidor_8c.html#a7fe9c3b755bbb7c1bfa37350473fc2c5',1,'recibirSolicitudEnListaSimple(t_listaSimple *listaSimple, t_nodo ***nodoDelCliente, char *bufferSolicitud):&#160;logicaServidor.c']]],
  ['recibirsolicitudentablahash_3',['recibirSolicitudEnTablaHash',['../logica_servidor_8h.html#a326ffb8f4ee3169f885ea692dbbc15e4',1,'recibirSolicitudEnTablaHash(t_tablaHash *tablaHash, t_nodo ***nodoDelCliente, char *bufferSolicitud):&#160;logicaServidor.c'],['../logica_servidor_8c.html#a326ffb8f4ee3169f885ea692dbbc15e4',1,'recibirSolicitudEnTablaHash(t_tablaHash *tablaHash, t_nodo ***nodoDelCliente, char *bufferSolicitud):&#160;logicaServidor.c']]],
  ['recursoscomunesautenticacionregistro_5fconfigurar_4',['recursosComunesAutenticacionRegistro_configurar',['../recursos_comunes_autenticacion_registro_8h.html#ad8b2ca3824eaa2323d4cf395d6da4e1e',1,'recursosComunesAutenticacionRegistro_configurar(t_recursosComunesAutenticacionRegistro *recursosComunesAutenticacionRegistro, const t_fuentes *fuentes):&#160;recursosComunesAutenticacionRegistro.c'],['../recursos_comunes_autenticacion_registro_8c.html#ad8b2ca3824eaa2323d4cf395d6da4e1e',1,'recursosComunesAutenticacionRegistro_configurar(t_recursosComunesAutenticacionRegistro *recursosComunesAutenticacionRegistro, const t_fuentes *fuentes):&#160;recursosComunesAutenticacionRegistro.c']]],
  ['recursoscomunesautenticacionregistro_5finicializar_5',['recursosComunesAutenticacionRegistro_inicializar',['../recursos_comunes_autenticacion_registro_8h.html#a27654fd5a07ccca29725d0569204f01a',1,'recursosComunesAutenticacionRegistro_inicializar(t_recursosComunesAutenticacionRegistro *recursosComunesAutenticacionRegistro):&#160;recursosComunesAutenticacionRegistro.c'],['../recursos_comunes_autenticacion_registro_8c.html#a27654fd5a07ccca29725d0569204f01a',1,'recursosComunesAutenticacionRegistro_inicializar(t_recursosComunesAutenticacionRegistro *recursosComunesAutenticacionRegistro):&#160;recursosComunesAutenticacionRegistro.c']]],
  ['recursoscomunesautenticacionregistro_5fliberar_6',['recursosComunesAutenticacionRegistro_liberar',['../recursos_comunes_autenticacion_registro_8h.html#a57ddf48bf5efa9de605f8e0bcf4404a3',1,'recursosComunesAutenticacionRegistro_liberar(t_recursosComunesAutenticacionRegistro *recursosComunesAutenticacionRegistro):&#160;recursosComunesAutenticacionRegistro.c'],['../recursos_comunes_autenticacion_registro_8c.html#a57ddf48bf5efa9de605f8e0bcf4404a3',1,'recursosComunesAutenticacionRegistro_liberar(t_recursosComunesAutenticacionRegistro *recursosComunesAutenticacionRegistro):&#160;recursosComunesAutenticacionRegistro.c']]],
  ['recursoscomunesautenticacionregistro_5frenderizarelementos_7',['recursosComunesAutenticacionRegistro_renderizarElementos',['../recursos_comunes_autenticacion_registro_8h.html#a6658f414e32d87e67f13d05656f10bfe',1,'recursosComunesAutenticacionRegistro_renderizarElementos(sfRenderWindow *renderizado, const t_recursosComunesAutenticacionRegistroElementos *elementos):&#160;recursosComunesAutenticacionRegistro.c'],['../recursos_comunes_autenticacion_registro_8c.html#a53ff113f1d3d5e373ee45d4bf8077a2e',1,'recursosComunesAutenticacionRegistro_renderizarElementos(sfRenderWindow *renderizado, const t_recursosComunesAutenticacionRegistroElementos *recursosComunesAutenticacionRegistroElementos):&#160;recursosComunesAutenticacionRegistro.c']]],
  ['recursoscomunesautenticacionregistro_5frenderizartextos_8',['recursosComunesAutenticacionRegistro_renderizarTextos',['../recursos_comunes_autenticacion_registro_8h.html#a49899c409597224e80c017f22be58b77',1,'recursosComunesAutenticacionRegistro_renderizarTextos(sfRenderWindow *renderizado, const t_recursosComunesAutenticacionRegistroTextos *textos):&#160;recursosComunesAutenticacionRegistro.c'],['../recursos_comunes_autenticacion_registro_8c.html#a49899c409597224e80c017f22be58b77',1,'recursosComunesAutenticacionRegistro_renderizarTextos(sfRenderWindow *renderizado, const t_recursosComunesAutenticacionRegistroTextos *textos):&#160;recursosComunesAutenticacionRegistro.c']]],
  ['recursoscomunescontactossalas_5fconfigurar_9',['recursosComunesContactosSalas_configurar',['../recursos_comunes_contactos_salas_8h.html#a81f0bda5272e22c13f4d70f85ddbc159',1,'recursosComunesContactosSalas_configurar(t_recursosComunesContactosSalas *recursosComunesContactosSalas, const t_fuentes *fuentes):&#160;recursosComunesContactosSalas.c'],['../recursos_comunes_contactos_salas_8c.html#a81f0bda5272e22c13f4d70f85ddbc159',1,'recursosComunesContactosSalas_configurar(t_recursosComunesContactosSalas *recursosComunesContactosSalas, const t_fuentes *fuentes):&#160;recursosComunesContactosSalas.c']]],
  ['recursoscomunescontactossalas_5finicializar_10',['recursosComunesContactosSalas_inicializar',['../recursos_comunes_contactos_salas_8h.html#aa13293a3acc907170756ef43e3967c6c',1,'recursosComunesContactosSalas_inicializar(t_recursosComunesContactosSalas *recursosComunesContactosSalas):&#160;recursosComunesContactosSalas.c'],['../recursos_comunes_contactos_salas_8c.html#aa13293a3acc907170756ef43e3967c6c',1,'recursosComunesContactosSalas_inicializar(t_recursosComunesContactosSalas *recursosComunesContactosSalas):&#160;recursosComunesContactosSalas.c']]],
  ['recursoscomunescontactossalas_5fliberar_11',['recursosComunesContactosSalas_liberar',['../recursos_comunes_contactos_salas_8h.html#afdc8cdcf913f6c2b0380f156d59a0995',1,'recursosComunesContactosSalas_liberar(t_recursosComunesContactosSalas *recursosComunesContactosSalas):&#160;recursosComunesContactosSalas.c'],['../recursos_comunes_contactos_salas_8c.html#afdc8cdcf913f6c2b0380f156d59a0995',1,'recursosComunesContactosSalas_liberar(t_recursosComunesContactosSalas *recursosComunesContactosSalas):&#160;recursosComunesContactosSalas.c']]],
  ['recursoscomunescontactossalas_5frenderizarelementos_12',['recursosComunesContactosSalas_renderizarElementos',['../recursos_comunes_contactos_salas_8h.html#a6b5fa280e6b2f561b389cdaaccf9841f',1,'recursosComunesContactosSalas_renderizarElementos(sfRenderWindow *renderizado, const t_recursosComunesContactosSalasElementos *elementos):&#160;recursosComunesContactosSalas.c'],['../recursos_comunes_contactos_salas_8c.html#a6b5fa280e6b2f561b389cdaaccf9841f',1,'recursosComunesContactosSalas_renderizarElementos(sfRenderWindow *renderizado, const t_recursosComunesContactosSalasElementos *elementos):&#160;recursosComunesContactosSalas.c']]],
  ['recursoscomunescontactossalas_5frenderizartextos_13',['recursosComunesContactosSalas_renderizarTextos',['../recursos_comunes_contactos_salas_8h.html#add796517dd6534dae013cfdf64ef9d7d',1,'recursosComunesContactosSalas_renderizarTextos(sfRenderWindow *renderizado, const t_recursosComunesContactosSalasTextos *textos):&#160;recursosComunesContactosSalas.c'],['../recursos_comunes_contactos_salas_8c.html#add796517dd6534dae013cfdf64ef9d7d',1,'recursosComunesContactosSalas_renderizarTextos(sfRenderWindow *renderizado, const t_recursosComunesContactosSalasTextos *textos):&#160;recursosComunesContactosSalas.c']]],
  ['reiniciarpuntoinsercion_14',['reiniciarPuntoInsercion',['../logica_usuario_8h.html#adf39ce9820bbd50d937a930be1507c43',1,'reiniciarPuntoInsercion(bool *puntoInsercion, unsigned short int *contadorPuntoInsercion):&#160;logicaUsuario.c'],['../logica_usuario_8c.html#adf39ce9820bbd50d937a930be1507c43',1,'reiniciarPuntoInsercion(bool *puntoInsercion, unsigned short int *contadorPuntoInsercion):&#160;logicaUsuario.c']]],
  ['renderizarlistamensajes_15',['renderizarListaMensajes',['../logica_usuario_8h.html#a5cf69ff9321deb67072fb7329dbf86e9',1,'renderizarListaMensajes(void *mensaje, void *renderizado):&#160;logicaUsuario.c'],['../logica_usuario_8c.html#a5cf69ff9321deb67072fb7329dbf86e9',1,'renderizarListaMensajes(void *mensaje, void *renderizado):&#160;logicaUsuario.c']]],
  ['renderizarlistanotificaciones_16',['renderizarListaNotificaciones',['../logica_usuario_8h.html#a3032a127d2a8337af90b103228fee96e',1,'renderizarListaNotificaciones(void *notificacion, void *renderizado):&#160;logicaUsuario.c'],['../logica_usuario_8c.html#a3032a127d2a8337af90b103228fee96e',1,'renderizarListaNotificaciones(void *notificacion, void *renderizado):&#160;logicaUsuario.c']]],
  ['renderizarnotificaciones_17',['renderizarNotificaciones',['../recursos_comunes_contactos_salas_8h.html#a4020d94be3355d7d3cf374cd353867fe',1,'renderizarNotificaciones(t_aplicacion *aplicacion, const t_recursosComunesContactosSalas *recursosComunesContactosSalas):&#160;recursosComunesContactosSalas.c'],['../recursos_comunes_contactos_salas_8c.html#a4020d94be3355d7d3cf374cd353867fe',1,'renderizarNotificaciones(t_aplicacion *aplicacion, const t_recursosComunesContactosSalas *recursosComunesContactosSalas):&#160;recursosComunesContactosSalas.c']]],
  ['renderizarvistamensajes_18',['renderizarVistaMensajes',['../recursos_comunes_contactos_salas_8h.html#a9cd3ad261eb37ac3545d8f3ccc39aced',1,'renderizarVistaMensajes(t_aplicacion *aplicacion, const t_recursosComunesContactosSalas *recursosComunesContactosSalas):&#160;recursosComunesContactosSalas.c'],['../recursos_comunes_contactos_salas_8c.html#a9cd3ad261eb37ac3545d8f3ccc39aced',1,'renderizarVistaMensajes(t_aplicacion *aplicacion, const t_recursosComunesContactosSalas *recursosComunesContactosSalas):&#160;recursosComunesContactosSalas.c']]]
];
