var searchData=
[
  ['recibirsolicitud_0',['recibirSolicitud',['../_pruebas_2_debug_usuario_2main_8c.html#a7663f006d9c623ea3bb76262b67d519b',1,'recibirSolicitud(SOCKET sock, char *bufferRespuesta):&#160;main.c'],['../_pruebas_2_debug_usuario_2main_8h.html#a7663f006d9c623ea3bb76262b67d519b',1,'recibirSolicitud(SOCKET sock, char *bufferRespuesta):&#160;main.c'],['../logica_usuario_8h.html#a7663f006d9c623ea3bb76262b67d519b',1,'recibirSolicitud(SOCKET sock, char *bufferRespuesta):&#160;main.c'],['../logica_usuario_8c.html#a7663f006d9c623ea3bb76262b67d519b',1,'recibirSolicitud(SOCKET sock, char *bufferRespuesta):&#160;logicaUsuario.c']]],
  ['recibirsolicitudenlistasimple_1',['recibirSolicitudEnListaSimple',['../logica_servidor_8h.html#a4d6ebef2ee3f0284f9a9c87f1ecce279',1,'recibirSolicitudEnListaSimple(s_listaSimple *listaSimple, s_nodo ***nodoDelCliente, char *bufferSolicitud):&#160;logicaServidor.c'],['../logica_servidor_8c.html#a4d6ebef2ee3f0284f9a9c87f1ecce279',1,'recibirSolicitudEnListaSimple(s_listaSimple *listaSimple, s_nodo ***nodoDelCliente, char *bufferSolicitud):&#160;logicaServidor.c']]],
  ['recibirsolicitudentablahash_2',['recibirSolicitudEnTablaHash',['../logica_servidor_8h.html#a9e87c0b7596ffa4d9c0e238e76a3d15d',1,'recibirSolicitudEnTablaHash(s_tablaHash *tablaHash, s_nodo ***nodoDelCliente, char *bufferSolicitud):&#160;logicaServidor.c'],['../logica_servidor_8c.html#a9e87c0b7596ffa4d9c0e238e76a3d15d',1,'recibirSolicitudEnTablaHash(s_tablaHash *tablaHash, s_nodo ***nodoDelCliente, char *bufferSolicitud):&#160;logicaServidor.c']]],
  ['recursoscomunesautenticacionregistro_5fconfigurar_3',['recursosComunesAutenticacionRegistro_configurar',['../recursos_comunes_autenticacion_registro_8h.html#a84394e36441d92b17aa642c563ff2084',1,'recursosComunesAutenticacionRegistro_configurar(s_recursosComunesAutenticacionRegistro *recursosComunesAutenticacionRegistro, s_fuentes fuentes, s_ventana ventana):&#160;recursosComunesAutenticacionRegistro.c'],['../recursos_comunes_autenticacion_registro_8c.html#a84394e36441d92b17aa642c563ff2084',1,'recursosComunesAutenticacionRegistro_configurar(s_recursosComunesAutenticacionRegistro *recursosComunesAutenticacionRegistro, s_fuentes fuentes, s_ventana ventana):&#160;recursosComunesAutenticacionRegistro.c']]],
  ['recursoscomunesautenticacionregistro_5finicializar_4',['recursosComunesAutenticacionRegistro_inicializar',['../recursos_comunes_autenticacion_registro_8h.html#aabcedc903e8ccd5ff2cb89eaeadcdc00',1,'recursosComunesAutenticacionRegistro_inicializar(s_recursosComunesAutenticacionRegistro *recursosComunesAutenticacionRegistro):&#160;recursosComunesAutenticacionRegistro.c'],['../recursos_comunes_autenticacion_registro_8c.html#aabcedc903e8ccd5ff2cb89eaeadcdc00',1,'recursosComunesAutenticacionRegistro_inicializar(s_recursosComunesAutenticacionRegistro *recursosComunesAutenticacionRegistro):&#160;recursosComunesAutenticacionRegistro.c']]],
  ['recursoscomunesautenticacionregistro_5fliberar_5',['recursosComunesAutenticacionRegistro_liberar',['../recursos_comunes_autenticacion_registro_8h.html#a44246354551c997a4234cb4010d81e19',1,'recursosComunesAutenticacionRegistro_liberar(s_recursosComunesAutenticacionRegistro *recursosComunesAutenticacionRegistro):&#160;recursosComunesAutenticacionRegistro.c'],['../recursos_comunes_autenticacion_registro_8c.html#a44246354551c997a4234cb4010d81e19',1,'recursosComunesAutenticacionRegistro_liberar(s_recursosComunesAutenticacionRegistro *recursosComunesAutenticacionRegistro):&#160;recursosComunesAutenticacionRegistro.c']]],
  ['recursoscomunescontactossalas_5fconfigurar_6',['recursosComunesContactosSalas_configurar',['../recursos_comunes_contactos_salas_8h.html#a53808faa261d01b24c61e0ee7d1aff5f',1,'recursosComunesContactosSalas_configurar(s_recursosComunesContactosSalas *recursosComunesContactosSalas, s_fuentes fuentes):&#160;recursosComunesContactosSalas.c'],['../recursos_comunes_contactos_salas_8c.html#a53808faa261d01b24c61e0ee7d1aff5f',1,'recursosComunesContactosSalas_configurar(s_recursosComunesContactosSalas *recursosComunesContactosSalas, s_fuentes fuentes):&#160;recursosComunesContactosSalas.c']]],
  ['recursoscomunescontactossalas_5finicializar_7',['recursosComunesContactosSalas_inicializar',['../recursos_comunes_contactos_salas_8h.html#a554444dea1c06fb0aa8e7d41af2dedf6',1,'recursosComunesContactosSalas_inicializar(s_recursosComunesContactosSalas *recursosComunesContactosSalas):&#160;recursosComunesContactosSalas.c'],['../recursos_comunes_contactos_salas_8c.html#a554444dea1c06fb0aa8e7d41af2dedf6',1,'recursosComunesContactosSalas_inicializar(s_recursosComunesContactosSalas *recursosComunesContactosSalas):&#160;recursosComunesContactosSalas.c']]],
  ['recursoscomunescontactossalas_5fliberar_8',['recursosComunesContactosSalas_liberar',['../recursos_comunes_contactos_salas_8h.html#a1a402bb174b0263b45df63aa6735bc78',1,'recursosComunesContactosSalas_liberar(s_recursosComunesContactosSalas *recursosComunesContactosSalas):&#160;recursosComunesContactosSalas.c'],['../recursos_comunes_contactos_salas_8c.html#a1a402bb174b0263b45df63aa6735bc78',1,'recursosComunesContactosSalas_liberar(s_recursosComunesContactosSalas *recursosComunesContactosSalas):&#160;recursosComunesContactosSalas.c']]],
  ['recursoscomunescontactossalas_5frenderizarelementos_9',['recursosComunesContactosSalas_renderizarElementos',['../recursos_comunes_contactos_salas_8h.html#af049200c69282e13de173f1861d0086b',1,'recursosComunesContactosSalas_renderizarElementos(sfRenderWindow *renderizado, const s_recursosComunesContactosSalasElementos *recursosComunesContactosSalasElementos):&#160;recursosComunesContactosSalas.c'],['../recursos_comunes_contactos_salas_8c.html#af049200c69282e13de173f1861d0086b',1,'recursosComunesContactosSalas_renderizarElementos(sfRenderWindow *renderizado, const s_recursosComunesContactosSalasElementos *recursosComunesContactosSalasElementos):&#160;recursosComunesContactosSalas.c']]],
  ['recursoscomunescontactossalas_5frenderizartexto_10',['recursosComunesContactosSalas_renderizarTexto',['../recursos_comunes_contactos_salas_8h.html#a19a19846c190342a0c60944b0ff6981d',1,'recursosComunesContactosSalas_renderizarTexto(sfRenderWindow *renderizado, const s_recursosComunesContactosSalasTexto *recursosComunesContactosSalasTexto):&#160;recursosComunesContactosSalas.c'],['../recursos_comunes_contactos_salas_8c.html#a19a19846c190342a0c60944b0ff6981d',1,'recursosComunesContactosSalas_renderizarTexto(sfRenderWindow *renderizado, const s_recursosComunesContactosSalasTexto *recursosComunesContactosSalasTexto):&#160;recursosComunesContactosSalas.c']]],
  ['recursoscomunescontactossalas_5ftamyposventana_11',['recursosComunesContactosSalas_tamYPosVentana',['../recursos_comunes_contactos_salas_8h.html#a502d0d37dba185e97623659aef3df1d2',1,'recursosComunesContactosSalas_tamYPosVentana(s_recursosComunesContactosSalas *recursosComunesContactosSalas, s_ventana ventana):&#160;recursosComunesContactosSalas.c'],['../recursos_comunes_contactos_salas_8c.html#a502d0d37dba185e97623659aef3df1d2',1,'recursosComunesContactosSalas_tamYPosVentana(s_recursosComunesContactosSalas *recursosComunesContactosSalas, s_ventana ventana):&#160;recursosComunesContactosSalas.c']]],
  ['renderizarlistamensajes_12',['renderizarListaMensajes',['../logica_usuario_8h.html#a5cf69ff9321deb67072fb7329dbf86e9',1,'renderizarListaMensajes(void *mensaje, void *renderizado):&#160;logicaUsuario.c'],['../logica_usuario_8c.html#a5cf69ff9321deb67072fb7329dbf86e9',1,'renderizarListaMensajes(void *mensaje, void *renderizado):&#160;logicaUsuario.c']]],
  ['renderizarlistanotificaciones_13',['renderizarListaNotificaciones',['../logica_usuario_8h.html#a3032a127d2a8337af90b103228fee96e',1,'renderizarListaNotificaciones(void *notificacion, void *renderizado):&#160;logicaUsuario.c'],['../logica_usuario_8c.html#a3032a127d2a8337af90b103228fee96e',1,'renderizarListaNotificaciones(void *notificacion, void *renderizado):&#160;logicaUsuario.c']]]
];
