var searchData=
[
  ['recibirrespuesta_0',['recibirRespuesta',['../logica_usuario_8h.html#a0e0bdec3b995275b2eacab27596c8555',1,'recibirRespuesta(SOCKET sock, char *bufferRespuesta):&#160;logicaUsuario.c'],['../logica_usuario_8c.html#a0e0bdec3b995275b2eacab27596c8555',1,'recibirRespuesta(SOCKET sock, char *bufferRespuesta):&#160;logicaUsuario.c']]],
  ['recibirsolicitud_1',['recibirSolicitud',['../_pruebas_2_debug_usuario_2main_8c.html#a7663f006d9c623ea3bb76262b67d519b',1,'recibirSolicitud(SOCKET sock, char *bufferRespuesta):&#160;main.c'],['../_pruebas_2_debug_usuario_2main_8h.html#a7663f006d9c623ea3bb76262b67d519b',1,'recibirSolicitud(SOCKET sock, char *bufferRespuesta):&#160;main.c']]],
  ['recibirsolicitudenlistasimple_2',['recibirSolicitudEnListaSimple',['../logica_servidor_8h.html#a4d6ebef2ee3f0284f9a9c87f1ecce279',1,'recibirSolicitudEnListaSimple(s_listaSimple *listaSimple, s_nodo ***nodoDelCliente, char *bufferSolicitud):&#160;logicaServidor.c'],['../logica_servidor_8c.html#a4d6ebef2ee3f0284f9a9c87f1ecce279',1,'recibirSolicitudEnListaSimple(s_listaSimple *listaSimple, s_nodo ***nodoDelCliente, char *bufferSolicitud):&#160;logicaServidor.c']]],
  ['recibirsolicitudentablahash_3',['recibirSolicitudEnTablaHash',['../logica_servidor_8h.html#a9e87c0b7596ffa4d9c0e238e76a3d15d',1,'recibirSolicitudEnTablaHash(s_tablaHash *tablaHash, s_nodo ***nodoDelCliente, char *bufferSolicitud):&#160;logicaServidor.c'],['../logica_servidor_8c.html#a9e87c0b7596ffa4d9c0e238e76a3d15d',1,'recibirSolicitudEnTablaHash(s_tablaHash *tablaHash, s_nodo ***nodoDelCliente, char *bufferSolicitud):&#160;logicaServidor.c']]],
  ['recursoscomunesautenticacionregistro_5fconfigurar_4',['recursosComunesAutenticacionRegistro_configurar',['../recursos_comunes_autenticacion_registro_8h.html#a2ecb8b8142fb419f983bb5236fea6eb4',1,'recursosComunesAutenticacionRegistro_configurar(s_recursosComunesAutenticacionRegistro *recursosComunesAutenticacionRegistro, const s_fuentes *fuentes):&#160;recursosComunesAutenticacionRegistro.c'],['../recursos_comunes_autenticacion_registro_8c.html#a2ecb8b8142fb419f983bb5236fea6eb4',1,'recursosComunesAutenticacionRegistro_configurar(s_recursosComunesAutenticacionRegistro *recursosComunesAutenticacionRegistro, const s_fuentes *fuentes):&#160;recursosComunesAutenticacionRegistro.c']]],
  ['recursoscomunesautenticacionregistro_5finicializar_5',['recursosComunesAutenticacionRegistro_inicializar',['../recursos_comunes_autenticacion_registro_8h.html#aabcedc903e8ccd5ff2cb89eaeadcdc00',1,'recursosComunesAutenticacionRegistro_inicializar(s_recursosComunesAutenticacionRegistro *recursosComunesAutenticacionRegistro):&#160;recursosComunesAutenticacionRegistro.c'],['../recursos_comunes_autenticacion_registro_8c.html#aabcedc903e8ccd5ff2cb89eaeadcdc00',1,'recursosComunesAutenticacionRegistro_inicializar(s_recursosComunesAutenticacionRegistro *recursosComunesAutenticacionRegistro):&#160;recursosComunesAutenticacionRegistro.c']]],
  ['recursoscomunesautenticacionregistro_5fliberar_6',['recursosComunesAutenticacionRegistro_liberar',['../recursos_comunes_autenticacion_registro_8h.html#a44246354551c997a4234cb4010d81e19',1,'recursosComunesAutenticacionRegistro_liberar(s_recursosComunesAutenticacionRegistro *recursosComunesAutenticacionRegistro):&#160;recursosComunesAutenticacionRegistro.c'],['../recursos_comunes_autenticacion_registro_8c.html#a44246354551c997a4234cb4010d81e19',1,'recursosComunesAutenticacionRegistro_liberar(s_recursosComunesAutenticacionRegistro *recursosComunesAutenticacionRegistro):&#160;recursosComunesAutenticacionRegistro.c']]],
  ['recursoscomunesautenticacionregistro_5frenderizarelementos_7',['recursosComunesAutenticacionRegistro_renderizarElementos',['../recursos_comunes_autenticacion_registro_8h.html#a86dab7c28baeea76138c8af7cf071c18',1,'recursosComunesAutenticacionRegistro_renderizarElementos(sfRenderWindow *renderizado, const s_recursosComunesAutenticacionRegistroElementos *recursosComunesAutenticacionRegistroElementos):&#160;recursosComunesAutenticacionRegistro.c'],['../recursos_comunes_autenticacion_registro_8c.html#a86dab7c28baeea76138c8af7cf071c18',1,'recursosComunesAutenticacionRegistro_renderizarElementos(sfRenderWindow *renderizado, const s_recursosComunesAutenticacionRegistroElementos *recursosComunesAutenticacionRegistroElementos):&#160;recursosComunesAutenticacionRegistro.c']]],
  ['recursoscomunesautenticacionregistro_5frenderizartexto_8',['recursosComunesAutenticacionRegistro_renderizarTexto',['../recursos_comunes_autenticacion_registro_8h.html#ab09c62d456ee80f1e3a7a4da3c5140de',1,'recursosComunesAutenticacionRegistro_renderizarTexto(sfRenderWindow *renderizado, const s_recursosComunesAutenticacionRegistroTexto *recursosComunesAutenticacionRegistroTexto):&#160;recursosComunesAutenticacionRegistro.c'],['../recursos_comunes_autenticacion_registro_8c.html#ab09c62d456ee80f1e3a7a4da3c5140de',1,'recursosComunesAutenticacionRegistro_renderizarTexto(sfRenderWindow *renderizado, const s_recursosComunesAutenticacionRegistroTexto *recursosComunesAutenticacionRegistroTexto):&#160;recursosComunesAutenticacionRegistro.c']]],
  ['recursoscomunescontactossalas_5fconfigurar_9',['recursosComunesContactosSalas_configurar',['../recursos_comunes_contactos_salas_8h.html#a0535d0e9d97855eab13e0fed2b803983',1,'recursosComunesContactosSalas_configurar(s_recursosComunesContactosSalas *recursosComunesContactosSalas, const s_fuentes *fuentes):&#160;recursosComunesContactosSalas.c'],['../recursos_comunes_contactos_salas_8c.html#a0535d0e9d97855eab13e0fed2b803983',1,'recursosComunesContactosSalas_configurar(s_recursosComunesContactosSalas *recursosComunesContactosSalas, const s_fuentes *fuentes):&#160;recursosComunesContactosSalas.c']]],
  ['recursoscomunescontactossalas_5finicializar_10',['recursosComunesContactosSalas_inicializar',['../recursos_comunes_contactos_salas_8h.html#a554444dea1c06fb0aa8e7d41af2dedf6',1,'recursosComunesContactosSalas_inicializar(s_recursosComunesContactosSalas *recursosComunesContactosSalas):&#160;recursosComunesContactosSalas.c'],['../recursos_comunes_contactos_salas_8c.html#a554444dea1c06fb0aa8e7d41af2dedf6',1,'recursosComunesContactosSalas_inicializar(s_recursosComunesContactosSalas *recursosComunesContactosSalas):&#160;recursosComunesContactosSalas.c']]],
  ['recursoscomunescontactossalas_5fliberar_11',['recursosComunesContactosSalas_liberar',['../recursos_comunes_contactos_salas_8h.html#a1a402bb174b0263b45df63aa6735bc78',1,'recursosComunesContactosSalas_liberar(s_recursosComunesContactosSalas *recursosComunesContactosSalas):&#160;recursosComunesContactosSalas.c'],['../recursos_comunes_contactos_salas_8c.html#a1a402bb174b0263b45df63aa6735bc78',1,'recursosComunesContactosSalas_liberar(s_recursosComunesContactosSalas *recursosComunesContactosSalas):&#160;recursosComunesContactosSalas.c']]],
  ['recursoscomunescontactossalas_5frenderizarelementos_12',['recursosComunesContactosSalas_renderizarElementos',['../recursos_comunes_contactos_salas_8h.html#af049200c69282e13de173f1861d0086b',1,'recursosComunesContactosSalas_renderizarElementos(sfRenderWindow *renderizado, const s_recursosComunesContactosSalasElementos *recursosComunesContactosSalasElementos):&#160;recursosComunesContactosSalas.c'],['../recursos_comunes_contactos_salas_8c.html#af049200c69282e13de173f1861d0086b',1,'recursosComunesContactosSalas_renderizarElementos(sfRenderWindow *renderizado, const s_recursosComunesContactosSalasElementos *recursosComunesContactosSalasElementos):&#160;recursosComunesContactosSalas.c']]],
  ['recursoscomunescontactossalas_5frenderizartexto_13',['recursosComunesContactosSalas_renderizarTexto',['../recursos_comunes_contactos_salas_8h.html#a19a19846c190342a0c60944b0ff6981d',1,'recursosComunesContactosSalas_renderizarTexto(sfRenderWindow *renderizado, const s_recursosComunesContactosSalasTexto *recursosComunesContactosSalasTexto):&#160;recursosComunesContactosSalas.c'],['../recursos_comunes_contactos_salas_8c.html#a19a19846c190342a0c60944b0ff6981d',1,'recursosComunesContactosSalas_renderizarTexto(sfRenderWindow *renderizado, const s_recursosComunesContactosSalasTexto *recursosComunesContactosSalasTexto):&#160;recursosComunesContactosSalas.c']]],
  ['recursoscomunescontactossalas_5ftamyposventana_14',['recursosComunesContactosSalas_tamYPosVentana',['../recursos_comunes_contactos_salas_8h.html#ab3f089423b0a1603346a5bfc0fe5dc75',1,'recursosComunesContactosSalas_tamYPosVentana(s_recursosComunesContactosSalas *recursosComunesContactosSalas, const s_ventana *ventana):&#160;recursosComunesContactosSalas.c'],['../recursos_comunes_contactos_salas_8c.html#ab3f089423b0a1603346a5bfc0fe5dc75',1,'recursosComunesContactosSalas_tamYPosVentana(s_recursosComunesContactosSalas *recursosComunesContactosSalas, const s_ventana *ventana):&#160;recursosComunesContactosSalas.c']]],
  ['reiniciarpuntoinsercion_15',['reiniciarPuntoInsercion',['../logica_usuario_8h.html#adf39ce9820bbd50d937a930be1507c43',1,'reiniciarPuntoInsercion(bool *puntoInsercion, unsigned short int *contadorPuntoInsercion):&#160;logicaUsuario.c'],['../logica_usuario_8c.html#adf39ce9820bbd50d937a930be1507c43',1,'reiniciarPuntoInsercion(bool *puntoInsercion, unsigned short int *contadorPuntoInsercion):&#160;logicaUsuario.c']]],
  ['renderizarlistamensajes_16',['renderizarListaMensajes',['../logica_usuario_8h.html#a5cf69ff9321deb67072fb7329dbf86e9',1,'renderizarListaMensajes(void *mensaje, void *renderizado):&#160;logicaUsuario.c'],['../logica_usuario_8c.html#a5cf69ff9321deb67072fb7329dbf86e9',1,'renderizarListaMensajes(void *mensaje, void *renderizado):&#160;logicaUsuario.c']]],
  ['renderizarlistanotificaciones_17',['renderizarListaNotificaciones',['../logica_usuario_8h.html#a3032a127d2a8337af90b103228fee96e',1,'renderizarListaNotificaciones(void *notificacion, void *renderizado):&#160;logicaUsuario.c'],['../logica_usuario_8c.html#a3032a127d2a8337af90b103228fee96e',1,'renderizarListaNotificaciones(void *notificacion, void *renderizado):&#160;logicaUsuario.c']]]
];
